services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: inventory-rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin123
      - RABBITMQ_DEFAULT_VHOST=/
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - inventory-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "check_running"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s

  inventory-api:
    build:
      context: ./InventoryAPI
      dockerfile: Dockerfile
    container_name: inventory-api
    ports:
      - "7022:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Data Source=/app/data/inventory.db
      - RabbitMQ__HostName=rabbitmq
      - RabbitMQ__Port=5672
      - RabbitMQ__UserName=admin
      - RabbitMQ__Password=admin123
      - RabbitMQ__ExchangeName=inventory_exchange
    volumes:
      - inventory_data:/app/data
    networks:
      - inventory-network
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped

  notification-service:
    build:
      context: ./NotificationService
      dockerfile: Dockerfile
    container_name: notification-service
    ports:
      - "7002:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Data Source=/app/data/notifications.db
      - RabbitMQ__HostName=rabbitmq
      - RabbitMQ__Port=5672
      - RabbitMQ__UserName=admin
      - RabbitMQ__Password=admin123
      - RabbitMQ__ExchangeName=inventory_exchange
    volumes:
      - notification_data:/app/data
    networks:
      - inventory-network
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped

networks:
  inventory-network:
    driver: bridge

volumes:
  rabbitmq_data:
  inventory_data:
  notification_data:
